---
AllCops:
  DisplayCopNames: true
  NewCops: enable

Layout/IndentationConsistency:
  EnforcedStyle: indented_internal_methods

Layout/LineLength:
  Max: 80

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes
  Enabled: true

Style/StringLiterals:
  EnforcedStyle: double_quotes
  Enabled: true

Style/FrozenStringLiteralComment:
  EnforcedStyle: never
